# Site settings
title: n20u's GitHub Blog
description: 使用 Jekyll 创建的 GitHub Pages 博客
lang: zh-CN
date_format: "%Y, %b %e"
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: n20u
user_description: I\'m a Software Engineer, always searching for the next challenge; no task is too scary nor too difficult.
user_title: 孤单，是一个人的狂欢
email: gezhiwanhun@qq.com
repo: n20u.github.io

exclude: ['package.json', 'src' , 'node_modules']

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title

compress_html:
  clippings: all

paginate: 6

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji

cdn:
  jsdelivr:
    enabled: true

# Gitalk setting
clientID: 0d4bbf4e2e839017b19f
clientSecret: 9d7f3f7318c026a7a92d6e75ad659565d4f7ca38