# Site settings
title: n20u
description: follow the interest
lang: zh-CN
date_format: "%Y, %b %e"
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: n20u
user_description: To do, to be, to dream.
user_title: believer of loneliness
email: n20u@nerif.anonaddy.com
repo: n20u.github.io

exclude: ['package.json', 'src' , 'node_modules']

# BUILD SETTINGS
# markdown: kramdown
# highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

permalink: /:title

compress_html:
  clippings: all

paginate: 6

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji

cdn:
  jsdelivr:
    enabled: true

# Gitalk setting
clientID: 0d4bbf4e2e839017b19f
clientSecret: 9d7f3f7318c026a7a92d6e75ad659565d4f7ca38

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"